---
abstract: 'Salvation::Autotype itself'
author:
  - 'Gennadiy Filatov <kain.winterheart@gmail.com>'
build_requires: {}
configure_requires:
  Module::Build: 0.36
dynamic_config: 1
generated_by: 'Module::Build version 0.4004, CPAN::Meta::Converter version 2.130880'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Salvation-Autotype
provides:
  Salvation::Autotype:
    file: lib/Salvation/Autotype.pm
    version: 1
  Salvation::Autotype::TypeConstraint:
    file: lib/Salvation/Autotype/TypeConstraint.pm
requires:
  Carp::Assert: 0.20
  Moose: 2.0402
  perl: v5.10.1
version: 1
